export interface GlossaryItem {
  id: string;
  category: 'polisemia' | 'sinonimos' | 'antonimos' | 'familia' | 'campo';
  categoryLabelEs: string;
  categoryLabelHy: string;
  titleEs: string;
  titleHy: string;
  detailEs: string;
  detailHy: string;
}

export const glossaryItems: GlossaryItem[] = [
  // Polisemia
  {
    id: 'p1',
    category: 'polisemia',
    categoryLabelEs: 'Polisemia',
    categoryLabelHy: 'Բազմիմաստություն',
    titleEs: 'banco',
    titleHy: 'նստարան / բանկ',
    detailEs: '1. Asiento para descansar en el parque. 2. Entidad financiera para guardar o sacar dinero.',
    detailHy: '1. Նստարան՝ այգում նստելու համար։ 2. Բանկ՝ գումար պահելու կամ հանելու ֆինանսական հիմնարկ։',
  },
  {
    id: 'p2',
    category: 'polisemia',
    categoryLabelEs: 'Polisemia',
    categoryLabelHy: 'Բազմիմաստություն',
    titleEs: 'gato',
    titleHy: 'կատու / ամբարձիկ (դոմկրատ)',
    detailEs: '1. Animal felino doméstico. 2. Herramienta mecánica para levantar un coche.',
    detailHy: '1. Տնային կատու (կենդանի)։ 2. Ամբարձիկ (դոմկրատ)՝ ավտոմեքենայի անիվը փոխելիս բարձրացնելու գործիք։',
  },
  {
    id: 'p3',
    category: 'polisemia',
    categoryLabelEs: 'Polisemia',
    categoryLabelHy: 'Բազմիմաստություն',
    titleEs: 'cabeza',
    titleHy: 'գլուխ / ղեկավար',
    detailEs: '1. Parte superior del cuerpo. 2. Jefe o persona que dirige un grupo.',
    detailHy: '1. Մարմնի վերին մաս (գլուխ)։ 2. Ղեկավար կամ խմբի գլխավոր անձ։',
  },
  {
    id: 'p4',
    category: 'polisemia',
    categoryLabelEs: 'Polisemia',
    categoryLabelHy: 'Բազմիմաստություն',
    titleEs: 'hoja',
    titleHy: 'տերև / թուղթ / շեղբ',
    detailEs: '1. Parte vegetal de un árbol. 2. Lámina de papel para escribir. 3. Parte cortante de un cuchillo.',
    detailHy: '1. Ծառի տերև։ 2. Գրելու թուղթ (էջ)։ 3. Դանակի սայր/շեղբ։',
  },
  {
    id: 'p5',
    category: 'polisemia',
    categoryLabelEs: 'Homonimia',
    categoryLabelHy: 'Համանունություն',
    titleEs: 'vino',
    titleHy: 'եկավ (գալ բայ) / գինի (ըմպելիք)',
    detailEs: '1. Forma del verbo venir (Juan vino ayer). 2. Bebida fermentada de uva (Bebieron vino).',
    detailHy: '1. «Venir» (գալ) բայի անցյալ ձևը (Juan vino ayer)։ 2. Խաղողի գինի (Bebieron vino)։',
  },

  // Sinónimos
  {
    id: 's1',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'feliz – contento',
    titleHy: 'ուրախ – գոհ / ուրախ',
    detailEs: 'Expresan estado de satisfacción y alegría.',
    detailHy: 'Արտահայտում են գոհունակություն և ուրախ տրամադրություն։',
  },
  {
    id: 's2',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'rápido – veloz',
    titleHy: 'արագ – սրընթաց',
    detailEs: 'Desplazamiento a gran velocidad.',
    detailHy: 'Մեծ արագությամբ տեղաշարժ։',
  },
  {
    id: 's3',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'bonito – hermoso',
    titleHy: 'գեղեցիկ – հիասքանչ',
    detailEs: 'Cualidad visual atractiva y agradable.',
    detailHy: 'Հաճելի և գրավիչ տեսք։',
  },
  {
    id: 's4',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'empezar – comenzar',
    titleHy: 'սկսել – սկսել',
    detailEs: 'Dar principio a una actividad.',
    detailHy: 'Որևէ գործողություն սկսել։',
  },
  {
    id: 's5',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'difícil – complicado',
    titleHy: 'դժվար – բարդ',
    detailEs: 'Que requiere esfuerzo o no es sencillo.',
    detailHy: 'Ջանք պահանջող, ոչ պարզ։',
  },
  {
    id: 's6',
    category: 'sinonimos',
    categoryLabelEs: 'Sinónimo',
    categoryLabelHy: 'Հոմանիշ',
    titleEs: 'alegre – contento',
    titleHy: 'ուրախ – գոհ',
    detailEs: 'Ánimo risueño y festivo.',
    detailHy: 'Ուրախ և զվարթ տրամադրություն։',
  },

  // Antónimos
  {
    id: 'a1',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'grande – pequeño',
    titleHy: 'մեծ – փոքր',
    detailEs: 'Oposición de tamaño.',
    detailHy: 'Չափսի հակադրություն։',
  },
  {
    id: 'a2',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'entrar – salir',
    titleHy: 'մտնել – դուրս գալ',
    detailEs: 'Oposición de dirección de movimiento.',
    detailHy: 'Շարժման ուղղության հակադրություն։',
  },
  {
    id: 'a3',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'fácil – difícil',
    titleHy: 'հեշտ – դժվար',
    detailEs: 'Oposición de nivel de dificultad.',
    detailHy: 'Բարդության աստիճանի հակադրություն։',
  },
  {
    id: 'a4',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'subir – bajar',
    titleHy: 'բարձրանալ – իջնել',
    detailEs: 'Oposición de desplazamiento vertical.',
    detailHy: 'Ուղղահայաց տեղաշարժի հակադրություն։',
  },
  {
    id: 'a5',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'cerca – lejos',
    titleHy: 'մոտ – հեռու',
    detailEs: 'Oposición de distancia.',
    detailHy: 'Հեռավորության հակադրություն։',
  },
  {
    id: 'a6',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'encender – apagar',
    titleHy: 'միացնել (վառել) – անջատել (մարել)',
    detailEs: 'Oposición de activación eléctrica o fuego.',
    detailHy: 'Միացնելու և անջատելու հակադրություն։',
  },
  {
    id: 'a7',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'lleno – vacío',
    titleHy: 'լեցուն (լիքը) – դատարկ',
    detailEs: 'Oposición de capacidad ocupada.',
    detailHy: 'Տարողունակության հակադրություն։',
  },
  {
    id: 'a8',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'frío – caliente',
    titleHy: 'սառը – տաք',
    detailEs: 'Oposición térmica.',
    detailHy: 'Ջերմաստիճանի հակադրություն։',
  },
  {
    id: 'a9',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'temprano – tarde',
    titleHy: 'շուտ – ուշ',
    detailEs: 'Oposición de momento temporal.',
    detailHy: 'Ժամանակի հակադրություն։',
  },
  {
    id: 'a10',
    category: 'antonimos',
    categoryLabelEs: 'Antónimo',
    categoryLabelHy: 'Հականիշ',
    titleEs: 'tranquilo – agitado',
    titleHy: 'հանգիստ – ալեկոծ',
    detailEs: 'Oposición de estado de calma o alteración.',
    detailHy: 'Հանդարտության և ալեկոծության հակադրություն։',
  },

  // Familias léxicas
  {
    id: 'f1',
    category: 'familia',
    categoryLabelEs: 'Familia léxica',
    categoryLabelHy: 'Բառակազմական ընտանիք',
    titleEs: 'pan – panadero – panadería',
    titleHy: 'հաց – հացթուխ – հացատուն/փուռ',
    detailEs: 'Raíz léxica compartida: «pan-».',
    detailHy: 'Ընդհանուր արմատ՝ «pan-»։',
  },
  {
    id: 'f2',
    category: 'familia',
    categoryLabelEs: 'Familia léxica',
    categoryLabelHy: 'Բառակազմական ընտանիք',
    titleEs: 'flor – florero – florista – florecer',
    titleHy: 'ծաղիկ – ծաղկաման – ծաղկավաճառ – ծաղկել',
    detailEs: 'Raíz léxica compartida: «flor-».',
    detailHy: 'Ընդհանուր արմատ՝ «flor-»։',
  },
  {
    id: 'f3',
    category: 'familia',
    categoryLabelEs: 'Familia léxica',
    categoryLabelHy: 'Բառակազմական ընտանիք',
    titleEs: 'mar – marinero – marítimo – marea',
    titleHy: 'ծով – նավաստի – ծովային – մակընթացություն',
    detailEs: 'Raíz léxica compartida: «mar-».',
    detailHy: 'Ընդհանուր արմատ՝ «mar-»։',
  },

  // Campos semánticos
  {
    id: 'c1',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Deportes: fútbol, tenis, baloncesto, natación',
    titleHy: 'Սպորտ՝ ֆուտբոլ, թենիս, բասկետբոլ, լող',
    detailEs: 'Pertenecen al tema común de la actividad física y el deporte.',
    detailHy: 'Պատկանում են սպորտային մարզաձևերի ընդհանուր թեմային։',
  },
  {
    id: 'c2',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Colores: rojo, azul, verde, amarillo',
    titleHy: 'Գույներ՝ կարմիր, կապույտ, կանաչ, դեղին',
    detailEs: 'Pertenecen a la categoría cromática visual.',
    detailHy: 'Պատկանում են գունային կարգին։',
  },
  {
    id: 'c3',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Medios de transporte: tren, avión, autobús, bicicleta',
    titleHy: 'Տրանսպորտ՝ գնացք, ինքնաթիռ, ավտոբուս, հեծանիվ',
    detailEs: 'Vehículos empleados para desplazarse.',
    detailHy: 'Տեղաշարժվելու համար նախատեսված փոխադրամիջոցներ։',
  },
  {
    id: 'c4',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Árboles: pinos, robles, olivos',
    titleHy: 'Ծառեր՝ սոճիներ, կաղնիներ, ձիթենիներ',
    detailEs: 'Especies vegetales del reino vegetal arbóreo.',
    detailHy: 'Ծառատեսակներ։',
  },
  {
    id: 'c5',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Animales marinos: peces, delfines, tortugas',
    titleHy: 'Ծովային կենդանիներ՝ ձկներ, դելֆիններ, կրիաներ',
    detailEs: 'Seres vivos que habitan en el mar y el océano.',
    detailHy: 'Ծովային և օվկիանոսային կենդանատեսակներ։',
  },
  {
    id: 'c6',
    category: 'campo',
    categoryLabelEs: 'Campo semántico',
    categoryLabelHy: 'Իմաստային դաշտ',
    titleEs: 'Muebles: mesa, silla, armario, sofá',
    titleHy: 'Կահույք՝ սեղան, աթոռ, պահարան, բազմոց',
    detailEs: 'Objetos para amueblar una casa u oficina.',
    detailHy: 'Տան կամ աշխատավայրի կահավորման առարկաներ։',
  },
];
