import { ExamText } from './types.ts';

export const examTexts: ExamText[] = [
  {
    id: 1,
    titleEs: 'Texto 1 — Una tarde en el parque',
    titleHy: 'Տեքստ 1 — Կեսօր այգում',
    textEs: [
      'El sábado, Carlos salió de casa muy contento porque había terminado todos sus deberes. Su hermana Elena también estaba feliz, así que decidieron ir juntos al parque.',
      'Primero pasaron por el banco para sacar dinero. Después llegaron al parque y se sentaron en un banco cerca de un árbol.',
      'El parque era muy grande, pero la zona de juegos infantiles era bastante pequeña. Cerca de ellos había niños que jugaban al fútbol, al baloncesto y al tenis.',
      'Más tarde compraron pan en una pequeña panadería. El panadero les dijo que acababa de preparar el pan.',
      'Al final de la tarde, Carlos dijo:',
      '—Ha sido un día muy bonito.',
      'Elena respondió:',
      '—Sí, ha sido un día realmente hermoso.',
    ],
    textHy: [
      'Շաբաթ օրը Կառլոսը շատ ուրախ դուրս եկավ տնից, որովհետև ավարտել էր բոլոր տնային աշխատանքները։ Նրա քույր Ելենան նույնպես ուրախ էր, և նրանք որոշեցին միասին գնալ այգի։',
      'Սկզբում նրանք անցան բանկով՝ գումար հանելու համար։ Հետո հասան այգի և նստեցին մի նստարանի վրա՝ ծառի մոտ։',
      'Այգին շատ մեծ էր, բայց մանկական խաղահրապարակը բավական փոքր էր։ Նրանց մոտ երեխաները խաղում էին ֆուտբոլ, բասկետբոլ և թենիս։',
      'Ավելի ուշ նրանք հաց գնեցին փոքրիկ հացատնից։ Հացթուխը ասաց, որ հենց նոր էր պատրաստել հացը։',
      'Օրվա վերջում Կառլոսն ասաց․',
      '— Շատ գեղեցիկ օր էր։',
      'Ելենան պատասխանեց․',
      '— Այո՛, իսկապես շատ հիասքանչ օր էր։',
    ],
    questions: [
      {
        id: 1,
        questionEs: '1. Busca dos sinónimos relacionados con la alegría.',
        questionHy: '1. Գտի՛ր ուրախություն արտահայտող երկու հոմանիշ։',
        answerEs: 'contento – feliz → sinónimos.',
        answerHy: 'contento – feliz → հոմանիշներ։',
      },
      {
        id: 2,
        questionEs: '2. Busca dos antónimos.',
        questionHy: '2. Գտի՛ր երկու հականիշ։',
        answerEs: 'grande – pequeña → antónimos.',
        answerHy: 'grande – pequeña → հականիշներ։',
      },
      {
        id: 3,
        questionEs: '3. Busca una palabra polisémica que aparezca dos veces con significados diferentes.',
        questionHy: '3. Գտի՛ր բազմիմաստ բառ, որը երկու անգամ օգտագործվում է տարբեր իմաստներով։',
        answerEs: 'banco → palabra polisémica.',
        answerHy: 'banco → բազմիմաստ բառ։',
      },
      {
        id: 4,
        questionEs: '4. Explica los dos significados de esa palabra.',
        questionHy: '4. Բացատրի՛ր այդ բառի երկու իմաստները։',
        answerEs: 'banco = entidad financiera (sacar dinero) / asiento del parque.',
        answerHy: 'banco = բանկ (դրամատուն) / նստարան (այգում)։',
      },
      {
        id: 5,
        questionEs: '5. Busca tres palabras que formen un campo semántico de los deportes.',
        questionHy: '5. Գտի՛ր սպորտի իմաստային դաշտին պատկանող երեք բառ։',
        answerEs: 'fútbol – baloncesto – tenis → campo semántico de los deportes.',
        answerHy: 'fútbol – baloncesto – tenis → սպորտի իմաստային դաշտ։',
      },
      {
        id: 6,
        questionEs: '6. Busca tres palabras de la misma familia léxica.',
        questionHy: '6. Գտի՛ր նույն բառակազմական ընտանիքին պատկանող երեք բառ։',
        answerEs: 'pan – panadero – panadería → familia léxica (raíz: pan-).',
        answerHy: 'pan – panadero – panadería → բառակազմական ընտանիք (արմատ՝ pan-)։',
      },
      {
        id: 7,
        questionEs: '7. Busca otros dos sinónimos al final del texto.',
        questionHy: '7. Տեքստի վերջում գտի՛ր ևս երկու հոմանիշ։',
        answerEs: 'bonito – hermoso → sinónimos.',
        answerHy: 'bonito – hermoso → հոմանիշներ։',
      },
    ],
  },
  {
    id: 2,
    titleEs: 'Texto 2 — En el colegio',
    titleHy: 'Տեքստ 2 — Դպրոցում',
    textEs: [
      'Esta mañana, Marta llegó temprano al colegio, pero su amigo Sergio llegó tarde. Los dos tenían un examen y estaban bastante preocupados.',
      'La profesora explicó que el ejercicio podía ser fácil para algunos alumnos y más difícil para otros.',
      'Durante el recreo, Marta abrió su libro y encontró una hoja entre las páginas. Después salió al patio y vio caer una hoja de un árbol.',
      'Cerca del patio había pinos, robles y olivos. Marta comentó que le gustaban mucho los árboles.',
      'Después de clase fue a la biblioteca. Allí encontró un libro rápido de leer porque era muy corto. Sergio dijo que sería una lectura veloz, aunque después los dos se rieron porque esa expresión sonaba un poco extraña.',
    ],
    textHy: [
      'Այսօր առավոտ Մարտան դպրոց շուտ հասավ, իսկ նրա ընկեր Սերխիոն՝ ուշ։ Երկուսն էլ քննություն ունեին և բավական անհանգիստ էին։',
      'Ուսուցչուհին բացատրեց, որ վարժությունը որոշ աշակերտների համար կարող է հեշտ լինել, իսկ մյուսների համար՝ ավելի դժվար։',
      'Դասամիջոցի ժամանակ Մարտան բացեց գիրքը և էջերի միջև մի թուղթ գտավ։ Հետո դուրս եկավ բակ և տեսավ ծառից ընկնող մի տերև։ Իսպաներենում երկու դեպքում էլ օգտագործվում է «hoja» բառը։',
      'Բակի մոտ կային սոճիներ, կաղնիներ և ձիթենիներ։ Մարտան նշեց, որ շատ է սիրում ծառերը։',
      'Դասերից հետո նա գնաց գրադարան։ Այնտեղ գտավ արագ ընթերցվող գիրք, որովհետև այն շատ կարճ էր։ Սերխիոն ասաց, որ դա սրընթաց ընթերցանություն կլինի, չնայած հետո երկուսն էլ ծիծաղեցին, որովհետև այդ արտահայտությունը մի փոքր տարօրինակ էր հնչում։',
    ],
    questions: [
      {
        id: 8,
        questionEs: '8. Busca un par de antónimos relacionado con el tiempo.',
        questionHy: '8. Գտի՛ր ժամանակի հետ կապված մեկ զույգ հականիշ։',
        answerEs: 'temprano – tarde → antónimos.',
        answerHy: 'temprano (շուտ) – tarde (ուշ) → հականիշներ։',
      },
      {
        id: 9,
        questionEs: '9. Busca otro par de antónimos relacionado con la dificultad.',
        questionHy: '9. Գտի՛ր բարդության հետ կապված մեկ այլ զույգ հականիշ։',
        answerEs: 'fácil – difícil → antónimos.',
        answerHy: 'fácil (հեշտ) – difícil (դժվար) → հականիշներ։',
      },
      {
        id: 10,
        questionEs: '10. ¿Qué palabra aparece con dos significados diferentes?',
        questionHy: '10. Ո՞ր բառն է հանդիպում երկու տարբեր իմաստներով։',
        answerEs: 'hoja → palabra polisémica.',
        answerHy: 'hoja → բազմիմաստ բառ։',
      },
      {
        id: 11,
        questionEs: '11. ¿Qué significa esa palabra en cada caso?',
        questionHy: '11. Ի՞նչ է նշանակում այդ բառը յուրաքանչյուր դեպքում։',
        answerEs: 'hoja de un libro/papel = lámina fina de papel; hoja de un árbol = órgano vegetal.',
        answerHy: 'hoja de libro/papel = թուղթ / էջ; hoja de un árbol = ծառի տերև։',
      },
      {
        id: 12,
        questionEs: '12. Busca tres palabras del campo semántico de los árboles.',
        questionHy: '12. Գտի՛ր ծառերի իմաստային դաշտին պատկանող երեք բառ։',
        answerEs: 'pinos – robles – olivos → campo semántico de los árboles.',
        answerHy: 'pinos (սոճիներ) – robles (կաղնիներ) – olivos (ձիթենիներ) → ծառերի իմաստային դաշտ։',
      },
    ],
  },
  {
    id: 3,
    titleEs: 'Texto 3 — Tipo examen (El mar)',
    titleHy: 'Տեքստ 3 — Քննության ձևաչափով (Ծովը)',
    textEs: [
      'Lucía vive cerca del mar. Su padre es marinero y uno de sus hermanos estudia biología marina. En verano toda la familia pasa mucho tiempo junto al mar.',
      'A Lucía le gusta observar los animales. A veces ve peces, delfines y tortugas.',
      'Una mañana el mar estaba muy tranquilo, pero por la tarde estaba bastante agitado.',
      'Lucía estaba alegre porque podía salir a pasear. Su hermano también estaba contento.',
    ],
    textHy: [
      'Լուսիան ապրում է ծովի մոտ։ Նրա հայրը նավաստի է, իսկ եղբայրներից մեկը ուսումնասիրում է ծովային կենսաբանություն։ Ամռանը ամբողջ ընտանիքը շատ ժամանակ է անցկացնում ծովի մոտ։',
      'Լուսիան սիրում է կենդանիներ դիտել։ Երբեմն նա տեսնում է ձկներ, դելֆիններ և կրիաներ։',
      'Մի առավոտ ծովը շատ հանգիստ էր, բայց կեսօրից հետո բավական ալեկոծ էր։',
      'Լուսիան ուրախ էր, որովհետև կարող էր զբոսնել։ Նրա եղբայրը նույնպես ուրախ էր։',
    ],
    questions: [
      {
        id: 13,
        questionEs: '13. Encuentra tres palabras de la misma familia léxica.',
        questionHy: '13. Գտի՛ր նույն բառակազմական ընտանիքին պատկանող երեք բառ։',
        answerEs: 'mar – marinero – marina → familia léxica.',
        answerHy: 'mar – marinero – marina → բառակազմական ընտանիք (արմատ՝ mar-)։',
      },
      {
        id: 14,
        questionEs: '14. Encuentra tres palabras del mismo campo semántico.',
        questionHy: '14. Գտի՛ր նույն իմաստային դաշտին պատկանող երեք բառ։',
        answerEs: 'peces – delfines – tortugas → campo semántico de los animales marinos.',
        answerHy: 'peces (ձկներ) – delfines (դելֆիններ) – tortugas (կրիաներ) → ծովային կենդանիների իմաստային դաշտ։',
      },
      {
        id: 15,
        questionEs: '15. Encuentra dos antónimos.',
        questionHy: '15. Գտի՛ր երկու հականիշ։',
        answerEs: 'tranquilo – agitado → antónimos.',
        answerHy: 'tranquilo (հանգիստ) – agitado (ալեկոծ) → հականիշներ։',
      },
      {
        id: 16,
        questionEs: '16. Encuentra dos sinónimos.',
        questionHy: '16. Գտի՛ր երկու հոմանիշ։',
        answerEs: 'alegre – contento → sinónimos.',
        answerHy: 'alegre – contento → հոմանիշներ։',
      },
      {
        id: 17,
        questionEs: '17. Explica la diferencia entre la familia léxica (pregunta 13) y el campo semántico (pregunta 14).',
        questionHy: '17. Բացատրի՛ր տարբերությունը 13-րդ հարցի բառակազմական ընտանիքի և 14-րդ հարցի իմաստային դաշտի միջև։',
        answerEs: 'En una familia léxica, las palabras comparten una raíz común: mar, marinero, marina. En un campo semántico, las palabras tienen significados relacionados con un mismo tema, aunque no comparten raíz: peces, delfines, tortugas.',
        answerHy: 'Բառակազմական ընտանիքում բառերն ունեն ընդհանուր արմատ՝ mar, marinero, marina։ Իմաստային դաշտում բառերը կապված են իմաստով (նույն թեման), բայց պարտադիր չէ նույն արմատն ունենան՝ peces, delfines, tortugas։',
      },
    ],
  },
];

export const examModel = {
  titleEs: 'Modelo de pregunta real de examen (1º ESO)',
  titleHy: 'Իրական քննության օրինակելի հարց (1º ESO / 7-րդ դասարան)',
  promptEs: 'Lee el texto y localiza: un par de sinónimos, un par de antónimos, una palabra polisémica, una familia léxica y un campo semántico. Justifica cada respuesta.',
  promptHy: 'Կարդա՛ տեքստը և գտի՛ր՝ մեկ զույգ հոմանիշ, մեկ զույգ հականիշ, մեկ բազմիմաստ բառ, մեկ բառակազմական ընտանիք և մեկ իմաստային դաշտ։ Հիմնավորի՛ր յուրաքանչյուր պատասխանը։',
  checklist: [
    {
      conceptEs: '1. Par de sinónimos',
      conceptHy: '1. Հոմանիշների զույգ',
      exampleEs: 'contento – feliz',
      justificationEs: 'Tienen significado semejante: expresan alegría o satisfacción.',
      justificationHy: 'Ունեն մոտ իմաստ՝ արտահայտում են ուրախություն։',
    },
    {
      conceptEs: '2. Par de antónimos',
      conceptHy: '2. Հականիշների զույգ',
      exampleEs: 'grande – pequeña (o temprano – tarde, tranquilo – agitado)',
      justificationEs: 'Expresan significados opuestos o contrarios en la misma escala.',
      justificationHy: 'Արտահայտում են տրամագծորեն հակառակ իմաստներ։',
    },
    {
      conceptEs: '3. Palabra polisémica',
      conceptHy: '3. Բազմիմաստ բառ',
      exampleEs: 'banco (entidad financiera / asiento) u hoja (papel / árbol)',
      justificationEs: 'Una misma palabra tiene más de un significado según el contexto en el que se utilice.',
      justificationHy: 'Նույն բառը տարբեր իրավիճակներում ունի տարբեր իմաստներ։',
    },
    {
      conceptEs: '4. Familia léxica',
      conceptHy: '4. Բառակազմական ընտանիք',
      exampleEs: 'pan – panadero – panadería (raíz pan-) o mar – marinero – marina (raíz mar-)',
      justificationEs: 'Conjunto de palabras que comparten la misma raíz morfológica (lexema).',
      justificationHy: 'Բառերի խումբ, որոնք ունեն ընդհանուր արմատ։',
    },
    {
      conceptEs: '5. Campo semántico',
      conceptHy: '5. Իմաստային դաշտ',
      exampleEs: 'fútbol, baloncesto, tenis (deportes) o peces, delfines, tortugas (animales marinos)',
      justificationEs: 'Palabras relacionadas por su significado (mismo tema o categoría), aunque tienen raíces distintas.',
      justificationHy: 'Նույն թեմային կամ կարգին պատկանող բառեր, թեև նրանց արմատները տարբեր են։',
    },
  ],
};
