import { ExerciseItem } from './types.ts';

export const practice2Items: ExerciseItem[] = [
  // Parte 1 — Elige la opción correcta / Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը
  {
    id: 1,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: '«bonito – hermoso» son:',
    questionHy: '«bonito – hermoso» զույգը հանդիսանում է՝',
    options: [
      { key: 'a', textEs: 'a) antónimos', textHy: 'հականիշներ' },
      { key: 'b', textEs: 'b) sinónimos', textHy: 'հոմանիշներ' },
      { key: 'c', textEs: 'c) homónimos', textHy: 'համանուններ' },
      { key: 'd', textEs: 'd) polisémicos', textHy: 'բազմիմաստներ' },
    ],
    answer: 'b) sinónimos',
    explanationEs: 'Ambos términos significan bello o de buen aspecto.',
    explanationHy: 'Երկու բառերն էլ նշանակում են գեղեցիկ, չքնաղ (հոմանիշներ)։',
  },
  {
    id: 2,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: '«entrar – salir» son:',
    questionHy: '«entrar – salir» (մտնել – դուրս գալ) զույգը հանդիսանում է՝',
    options: [
      { key: 'a', textEs: 'a) sinónimos', textHy: 'հոմանիշներ' },
      { key: 'b', textEs: 'b) antónimos', textHy: 'հականիշներ' },
      { key: 'c', textEs: 'c) familia léxica', textHy: 'բառակազմական ընտանիք' },
      { key: 'd', textEs: 'd) polisémicos', textHy: 'բազմիմաստներ' },
    ],
    answer: 'b) antónimos',
    explanationEs: 'Expresan acciones en direcciones opuestas.',
    explanationHy: 'Արտահայտում են հակառակ գործողություններ (հականիշներ)։',
  },
  {
    id: 3,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: 'Una palabra que tiene un solo significado principal se llama:',
    questionHy: 'Բառը, որն ունի միայն մեկ հիմնական իմաստ, կոչվում է՝',
    options: [
      { key: 'a', textEs: 'a) polisémica', textHy: 'բազմիմաստ' },
      { key: 'b', textEs: 'b) monosémica', textHy: 'մենիմաստ' },
      { key: 'c', textEs: 'c) sinónima', textHy: 'հոմանիշ' },
      { key: 'd', textEs: 'd) antónima', textHy: 'հականիշ' },
    ],
    answer: 'b) monosémica',
    explanationEs: 'Mono- significa uno solo: tiene un único significado.',
    explanationHy: '«Mono-» նշանակում է մեկ. մեկ իմաստ ունեցող բառ (մենիմաստ)։',
  },
  {
    id: 4,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: 'Una palabra con varios significados relacionados se llama:',
    questionHy: 'Մի քանի կապված իմաստներ ունեցող բառը կոչվում է՝',
    options: [
      { key: 'a', textEs: 'a) homónima', textHy: 'համանուն' },
      { key: 'b', textEs: 'b) polisémica', textHy: 'բազմիմաստ' },
      { key: 'c', textEs: 'c) antónima', textHy: 'հականիշ' },
      { key: 'd', textEs: 'd) derivada', textHy: 'ածանցյալ' },
    ],
    answer: 'b) polisémica',
    explanationEs: 'Tiene múltiples acepciones conectadas por semejanza o uso.',
    explanationHy: 'Այն ունի մի քանի իրար հետ կապված իմաստներ (բազմիմաստ)։',
  },
  {
    id: 5,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: '«flor, florista, florero» forman:',
    questionHy: '«flor, florista, florero» կազմում են՝',
    options: [
      { key: 'a', textEs: 'a) campo semántico', textHy: 'իմաստային դաշտ' },
      { key: 'b', textEs: 'b) familia léxica', textHy: 'բառակազմական ընտանիք' },
      { key: 'c', textEs: 'c) antonimia', textHy: 'հականիշություն' },
      { key: 'd', textEs: 'd) polisemia', textHy: 'բազմիմաստություն' },
    ],
    answer: 'b) familia léxica',
    explanationEs: 'Comparten la raíz común «flor-».',
    explanationHy: 'Ունեն ընդհանուր «flor-» արմատը, ուստի բառակազմական ընտանիք են։',
  },
  {
    id: 6,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la opción correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ տարբերակը',
    questionEs: '«mesa, silla, armario, sofá» forman:',
    questionHy: '«mesa, silla, armario, sofá» կազմում են՝',
    options: [
      { key: 'a', textEs: 'a) familia léxica', textHy: 'բառակազմական ընտանիք' },
      { key: 'b', textEs: 'b) campo semántico', textHy: 'իմաստային դաշտ' },
      { key: 'c', textEs: 'c) sinonimia', textHy: 'հոմանիշություն' },
      { key: 'd', textEs: 'd) antonimia', textHy: 'հականիշություն' },
    ],
    answer: 'b) campo semántico',
    explanationEs: 'Pertenecen al campo semántico de los muebles de una casa.',
    explanationHy: 'Կահույքի (muebles) իմաստային դաշտ՝ կապված են իմաստով, ոչ թե արմատով։',
  },

  // Parte 2 — Busca el sinónimo / Մաս 2 — Գտի՛ր հոմանիշը
  {
    id: 7,
    part: 2,
    partTitleEs: 'Parte 2 — Busca el sinónimo',
    partTitleHy: 'Մաս 2 — Գտի՛ր հոմանիշը',
    questionEs: 'feliz → __________ (🇦🇲 ուրախ → __________)',
    questionHy: 'feliz → գտի՛ր իսպաներեն հոմանիշը (ուրախ)',
    answer: 'contento',
    explanationEs: 'feliz y contento son sinónimos comunes.',
    explanationHy: 'feliz (ուրախ) → contento (գոհ/ուրախ)։',
  },
  {
    id: 8,
    part: 2,
    partTitleEs: 'Parte 2 — Busca el sinónimo',
    partTitleHy: 'Մաս 2 — Գտի՛ր հոմանիշը',
    questionEs: 'empezar → __________',
    questionHy: 'empezar (սկսել) → գտի՛ր հոմանիշը',
    answer: 'comenzar',
    explanationEs: 'empezar es sinónimo de comenzar.',
    explanationHy: 'empezar → comenzar (սկսել)։',
  },
  {
    id: 9,
    part: 2,
    partTitleEs: 'Parte 2 — Busca el sinónimo',
    partTitleHy: 'Մաս 2 — Գտի՛ր հոմանիշը',
    questionEs: 'rápido → __________',
    questionHy: 'rápido (արագ) → գտի՛ր հոմանիշը',
    answer: 'veloz',
    explanationEs: 'rápido es sinónimo de veloz.',
    explanationHy: 'rápido → veloz (սրընթաց)։',
  },
  {
    id: 10,
    part: 2,
    partTitleEs: 'Parte 2 — Busca el sinónimo',
    partTitleHy: 'Մաս 2 — Գտի՛ր հոմանիշը',
    questionEs: 'bonito → __________',
    questionHy: 'bonito (գեղեցիկ) → գտի՛ր հոմանիշը',
    answer: 'hermoso',
    explanationEs: 'bonito es sinónimo de hermoso o bello.',
    explanationHy: 'bonito → hermoso (հիասքանչ/գեղեցիկ)։',
  },

  // Parte 3 — Busca el antónimo / Մաս 3 — Գտի՛ր հականիշը
  {
    id: 11,
    part: 3,
    partTitleEs: 'Parte 3 — Busca el antónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հականիշը',
    questionEs: 'grande → __________',
    questionHy: 'grande (մեծ) → գտի՛ր հականիշը',
    answer: 'pequeño',
    explanationEs: 'Antónimo: pequeño.',
    explanationHy: 'մեծ (grande) → փոքր (pequeño)։',
  },
  {
    id: 12,
    part: 3,
    partTitleEs: 'Parte 3 — Busca el antónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հականիշը',
    questionEs: 'subir → __________',
    questionHy: 'subir (բարձրանալ) → գտի՛ր հականիշը',
    answer: 'bajar',
    explanationEs: 'Antónimo: bajar.',
    explanationHy: 'բարձրանալ (subir) → իջնել (bajar)։',
  },
  {
    id: 13,
    part: 3,
    partTitleEs: 'Parte 3 — Busca el antónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հականիշը',
    questionEs: 'lleno → __________',
    questionHy: 'lleno (լիքը/լեցուն) → գտի՛ր հականիշը',
    answer: 'vacío',
    explanationEs: 'Antónimo: vacío.',
    explanationHy: 'լեցուն (lleno) → դատարկ (vacío)։',
  },
  {
    id: 14,
    part: 3,
    partTitleEs: 'Parte 3 — Busca el antónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հականիշը',
    questionEs: 'cerca → __________',
    questionHy: 'cerca (մոտ) → գտի՛ր հականիշը',
    answer: 'lejos',
    explanationEs: 'Antónimo: lejos.',
    explanationHy: 'մոտ (cerca) → հեռու (lejos)։',
  },
  {
    id: 15,
    part: 3,
    partTitleEs: 'Parte 3 — Busca el antónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հականիշը',
    questionEs: 'encender → __________',
    questionHy: 'encender (վառել/միացնել) → գտի՛ր հականիշը',
    answer: 'apagar',
    explanationEs: 'Antónimo: apagar.',
    explanationHy: 'միացնել (encender) → անջատել (apagar)։',
  },

  // Parte 4 — Polisemia en contexto / Մաս 4 — Բազմիմաստ բառերը համատեքստում
  {
    id: 16,
    part: 4,
    partTitleEs: 'Parte 4 — Polisemia en contexto',
    partTitleHy: 'Մաս 4 — Բազմիմաստ բառերը համատեքստում',
    questionEs: '«El gato está debajo de la mesa.» ¿Qué significa «gato» aquí?',
    questionHy: '«Կատուն սեղանի տակ է»։ Ի՞նչ է նշանակում «gato» այստեղ։',
    options: [
      { key: 'a', textEs: 'a) animal', textHy: 'կենդանի (կատու)' },
      { key: 'b', textEs: 'b) herramienta para levantar un coche', textHy: 'մեքենան բարձրացնելու գործիք (ամբարձիկ)' },
      { key: 'c', textEs: 'c) bebida', textHy: 'ըմպելիք' },
      { key: 'd', textEs: 'd) edificio', textHy: 'շենք' },
    ],
    answer: 'a) animal',
    explanationEs: 'En esta frase se refiere al animal doméstico.',
    explanationHy: 'Նախադասության մեջ խոսքը տնային կենդանու մասին է։',
  },
  {
    id: 17,
    part: 4,
    partTitleEs: 'Parte 4 — Polisemia en contexto',
    partTitleHy: 'Մաս 4 — Բազմիմաստ բառերը համատեքստում',
    questionEs: '«Necesitamos un gato para cambiar la rueda del coche.» ¿Qué significa «gato»?',
    questionHy: '«Ավտոմեքենայի անիվը փոխելու համար մեզ gato է պետք»։ Ի՞նչ է նշանակում «gato»։',
    options: [
      { key: 'a', textEs: 'a) animal', textHy: 'կենդանի' },
      { key: 'b', textEs: 'b) herramienta', textHy: 'գործիք (դոմկրատ/ամբարձիկ)' },
      { key: 'c', textEs: 'c) asiento', textHy: 'նստարան' },
      { key: 'd', textEs: 'd) persona', textHy: 'անձ' },
    ],
    answer: 'b) herramienta',
    explanationEs: 'Se refiere al mecanismo elevador para levantar vehículos.',
    explanationHy: 'Այստեղ gato նշանակում է մեքենան բարձրացնելու գործիք (դոմկրատ)։',
  },
  {
    id: 18,
    part: 4,
    partTitleEs: 'Parte 4 — Polisemia en contexto',
    partTitleHy: 'Մաս 4 — Բազմիմաստ բառերը համատեքստում',
    questionEs: '«Tiene una hoja muy afilada.» ¿Qué puede significar «hoja»?',
    questionHy: '«Ունի շատ սուր hoja»։ Ի՞նչ կարող է նշանակել «hoja»։',
    options: [
      { key: 'a', textEs: 'a) hoja de árbol o de papel, según el contexto', textHy: 'ծառի տերև, թուղթ կամ դանակի շեղբ՝ ըստ համատեքստի' },
      { key: 'b', textEs: 'b) solo una persona', textHy: 'միայն մարդ' },
      { key: 'c', textEs: 'c) solo un verbo', textHy: 'միայն բայ' },
      { key: 'd', textEs: 'd) ningún significado', textHy: 'ոչ մի իմաստ' },
    ],
    answer: 'a)',
    explanationEs: 'Hoja es polisémica: hoja de árbol, hoja de papel o filo metálico.',
    explanationHy: 'hoja-ն բազմիմաստ է՝ տերև, թուղթ կամ սայր/շեղբ (կախված համատեքստից)։',
  },
  {
    id: 19,
    part: 4,
    partTitleEs: 'Parte 4 — Polisemia en contexto',
    partTitleHy: 'Մաս 4 — Բազմիմաստ բառերը համատեքստում',
    questionEs: '«La hoja del árbol cayó al suelo.» «hoja» significa: __________',
    questionHy: '«Ծառի hoja-ն ընկավ գետնին»։ «hoja» նշանակում է՝ __________',
    answer: 'parte del árbol',
    explanationEs: 'Se refiere a la hoja vegetal del árbol.',
    explanationHy: 'Ծառի տերև (ծառի բուսական մաս)։',
  },
  {
    id: 20,
    part: 4,
    partTitleEs: 'Parte 4 — Polisemia en contexto',
    partTitleHy: 'Մաս 4 — Բազմիմաստ բառերը համատեքստում',
    questionEs: '«Escribe tu nombre en una hoja.» «hoja» significa: __________',
    questionHy: '«Գրի՛ր անունդ մի hoja-ի վրա»։ «hoja» նշանակում է՝ __________',
    answer: 'hoja de papel',
    explanationEs: 'Se refiere a una lámina o pliego de papel para escribir.',
    explanationHy: 'Թուղթ, թերթ, գրելու էջ։',
  },

  // Parte 5 — Campo semántico / Մաս 5 — Իմաստային դաշտ
  {
    id: 21,
    part: 5,
    partTitleEs: 'Parte 5 — Campo semántico',
    partTitleHy: 'Մաս 5 — Իմաստային դաշտ',
    questionEs: '¿Qué palabra no pertenece al grupo? «manzana – pera – plátano – silla»',
    questionHy: 'Ո՞ր բառը չի պատկանում խմբին․ manzana (խնձոր) – pera (տանձ) – plátano (բանան) – silla (աթոռ)',
    answer: 'silla',
    explanationEs: 'Silla es un mueble; los demás son frutas comestibles.',
    explanationHy: 'silla (աթոռ)՝ կահույք է, մինչդեռ մյուսները մրգեր են։',
  },
  {
    id: 22,
    part: 5,
    partTitleEs: 'Parte 5 — Campo semántico',
    partTitleHy: 'Մաս 5 — Իմաստային դաշտ',
    questionEs: '«lunes, martes, miércoles, jueves» pertenecen al campo semántico de: __________',
    questionHy: '«lunes, martes, miércoles, jueves» պատկանում են ո՞ր իմաստային դաշտին․',
    answer: 'los días de la semana',
    explanationEs: 'Pertenecen a los días de la semana.',
    explanationHy: 'Շաբաթվա օրեր (los días de la semana)։',
  },
  {
    id: 23,
    part: 5,
    partTitleEs: 'Parte 5 — Campo semántico',
    partTitleHy: 'Մաս 5 — Իմաստային դաշտ',
    questionEs: '«rojo, verde, azul, amarillo» → __________',
    questionHy: '«rojo, verde, azul, amarillo» → ո՞ր իմաստային դաշտն են կազմում․',
    answer: 'colores',
    explanationEs: 'Campo semántico de los colores.',
    explanationHy: 'Գույներ (colores)։',
  },
  {
    id: 24,
    part: 5,
    partTitleEs: 'Parte 5 — Campo semántico',
    partTitleHy: 'Մաս 5 — Իմաստային դաշտ',
    questionEs: '«tren, avión, autobús, bicicleta» → __________',
    questionHy: '«tren, avión, autobús, bicicleta» → ո՞ր իմաստային դաշտն են կազմում․',
    answer: 'medios de transporte',
    explanationEs: 'Campo semántico de los medios de transporte.',
    explanationHy: 'Տրանսպորտային միջոցներ (medios de transporte)։',
  },

  // Parte 6 — Familia léxica / Մաս 6 — Բառակազմական ընտանիք
  {
    id: 25,
    part: 6,
    partTitleEs: 'Parte 6 — Familia léxica',
    partTitleHy: 'Մաս 6 — Բառակազմական ընտանիք',
    questionEs: 'Completa la familia de «mar»: mar – marinero – __________',
    questionHy: 'Լրացրո՛ւ «mar» (ծով) բառի ընտանիքը․ mar – marinero – __________',
    answer: 'marítimo',
    explanationEs: 'Respuesta posible: marítimo (también marea, submarino).',
    explanationHy: 'marítimo (ծովային) / marea (մակընթացություն)։',
  },
  {
    id: 26,
    part: 6,
    partTitleEs: 'Parte 6 — Familia léxica',
    partTitleHy: 'Մաս 6 — Բառակազմական ընտանիք',
    questionEs: 'Completa la familia de «pan»: pan – panadero – __________',
    questionHy: 'Լրացրո՛ւ «pan» (հաց) բառի ընտանիքը․ pan – panadero – __________',
    answer: 'panadería',
    explanationEs: 'Comparte la raíz pan- (panadería, empanar, panecillo).',
    explanationHy: 'panadería (հացատուն/փուռ)։',
  },
  {
    id: 27,
    part: 6,
    partTitleEs: 'Parte 6 — Familia léxica',
    partTitleHy: 'Մաս 6 — Բառակազմական ընտանիք',
    questionEs: '¿Cuál NO pertenece a la familia de «flor»?',
    questionHy: 'Ո՞ր բառը ՉԻ պատկանում «flor» (ծաղիկ) բառի ընտանիքին․',
    options: [
      { key: 'a', textEs: 'a) florista', textHy: 'florista (ծաղկավաճառ)' },
      { key: 'b', textEs: 'b) florero', textHy: 'florero (ծաղկաման)' },
      { key: 'c', textEs: 'c) florecer', textHy: 'florecer (ծաղկել)' },
      { key: 'd', textEs: 'd) jardín', textHy: 'jardín (այգի)' },
    ],
    answer: 'd) jardín',
    explanationEs: 'Jardín pertenece al mismo campo semántico o tema, pero no tiene la raíz «flor-».',
    explanationHy: 'jardín (այգի) չունի «flor-» արմատը, ուստի չի մտնում բառակազմական ընտանիքի մեջ։',
  },

  // Parte 7 — Texto tipo examen / Մաս 7 — Տեքստ՝ քննության նման
  {
    id: 28,
    part: 7,
    partTitleEs: 'Parte 7 — Texto tipo examen (Marta)',
    partTitleHy: 'Մաս 7 — Տեքստ՝ քննության նման (Մարտա)',
    questionEs: 'En el texto de Marta: Busca una palabra polisémica.',
    questionHy: 'Մարտայի տեքստից․ Գտի՛ր բազմիմաստ բառ։',
    answer: 'banco',
    explanationEs: 'Aparece dos veces con significados distintos: entidad bancaria y asiento.',
    explanationHy: 'banco (նախ՝ դրամատուն, ապա՝ նստարան)։',
  },
  {
    id: 29,
    part: 7,
    partTitleEs: 'Parte 7 — Texto tipo examen (Marta)',
    partTitleHy: 'Մաս 7 — Տեքստ՝ քննության նման (Մարտա)',
    questionEs: 'Explica los dos significados de «banco» en el texto de Marta.',
    questionHy: 'Բացատրի՛ր «banco» բառի երկու իմաստները Մարտայի տեքստում։',
    answer: '1. entidad financiera, 2. asiento',
    explanationEs: '1. Entidad financiera donde se saca dinero; 2. Asiento para descansar en el parque.',
    explanationHy: '1. բանկ (դրամատուն), 2. նստարան (այգում հանգստանալու տեղ)։',
  },
  {
    id: 30,
    part: 7,
    partTitleEs: 'Parte 7 — Texto tipo examen (Marta)',
    partTitleHy: 'Մաս 7 — Տեքստ՝ քննության նման (Մարտա)',
    questionEs: 'Busca dos sinónimos en el texto de Marta.',
    questionHy: 'Գտի՛ր երկու հոմանիշ Մարտայի տեքստում։',
    answer: 'contenta – feliz',
    explanationEs: 'Marta estaba «contenta» y su madre estaba «feliz».',
    explanationHy: 'contenta (գոհ/ուրախ) – feliz (ուրախ/երջանիկ)։',
  },
  {
    id: 31,
    part: 7,
    partTitleEs: 'Parte 7 — Texto tipo examen (Marta)',
    partTitleHy: 'Մաս 7 — Տեքստ՝ քննության նման (Մարտա)',
    questionEs: 'Busca dos adjetivos que puedan funcionar como contrarios en otros contextos.',
    questionHy: 'Գտի՛ր երկու ածական, որոնք այլ համատեքստում կարող են գործել որպես հակառակներ։',
    answer: 'estrecha – grande (pares léxicos: estrecha / ancha, grande / pequeña)',
    explanationEs: 'En el léxico los antónimos exactos son estrecha/ancha y grande/pequeña.',
    explanationHy: 'Տեքստում կան estrecha (նեղ) և grande (մեծ)։ Ճշգրիտ հականիշ զույգերն են՝ estrecha/ancha և grande/pequeña։',
  },

  // Parte 8 — Encuentra el intruso / Մաս 8 — Գտի՛ր ավելորդը
  {
    id: 32,
    part: 8,
    partTitleEs: 'Parte 8 — Encuentra el intruso',
    partTitleHy: 'Մաս 8 — Գտի՛ր ավելորդը',
    questionEs: 'feliz – alegre – contento – triste',
    questionHy: 'feliz – alegre – contento – triste → ո՞րն է ավելորդը',
    answer: 'triste',
    explanationEs: 'Triste es un antónimo de los otros tres, que expresan alegría.',
    explanationHy: 'triste (տխուր)՝ հականիշ է մյուս երեքին, որոնք ուրախություն են արտահայտում։',
  },
  {
    id: 33,
    part: 8,
    partTitleEs: 'Parte 8 — Encuentra el intruso',
    partTitleHy: 'Մաս 8 — Գտի՛ր ավելորդը',
    questionEs: 'grande – enorme – amplio – pequeño',
    questionHy: 'grande – enorme – amplio – pequeño → ո՞րն է ավելորդը',
    answer: 'pequeño',
    explanationEs: 'Pequeño significa de tamaño reducido; los otros tres indican gran tamaño.',
    explanationHy: 'pequeño (փոքր)՝ մյուս երեքը մեծ չափ են ցույց տալիս։',
  },
  {
    id: 34,
    part: 8,
    partTitleEs: 'Parte 8 — Encuentra el intruso',
    partTitleHy: 'Մաս 8 — Գտի՛ր ավելորդը',
    questionEs: 'correr – caminar – saltar – mesa',
    questionHy: 'correr – caminar – saltar – mesa → ո՞րն է ավելորդը',
    answer: 'mesa',
    explanationEs: 'Mesa es un objeto/sustantivo; los demás son verbos de movimiento físico.',
    explanationHy: 'mesa (սեղան)՝ գոյական է, իսկ մնացածը շարժում ցույց տվող բայեր են։',
  },
  {
    id: 35,
    part: 8,
    partTitleEs: 'Parte 8 — Encuentra el intruso',
    partTitleHy: 'Մաս 8 — Գտի՛ր ավելորդը',
    questionEs: 'avión – tren – barco – naranja',
    questionHy: 'avión – tren – barco – naranja → ո՞րն է ավելորդը',
    answer: 'naranja',
    explanationEs: 'Naranja es una fruta; los demás son medios de transporte.',
    explanationHy: 'naranja (նարինջ)՝ միրգ է, իսկ մնացածը տրանսպորտային միջոցներ են։',
  },

  // Parte 9 — Explica por qué / Մաս 9 — Բացատրի՛ր՝ ինչու
  {
    id: 36,
    part: 9,
    partTitleEs: 'Parte 9 — Explica por qué',
    partTitleHy: 'Մաս 9 — Բացատրի՛ր՝ ինչու',
    questionEs: '¿Por qué «feliz» y «contento» son sinónimos?',
    questionHy: 'Ինչո՞ւ են «feliz» և «contento» բառերը հոմանիշներ։',
    answer: 'Porque tienen un significado parecido.',
    explanationEs: 'Ambos transmiten la emoción positiva de satisfacción y alegría.',
    explanationHy: 'Որովհետև ունեն մոտ իմաստ (արտահայտում են ուրախության զգացում)։',
  },
  {
    id: 37,
    part: 9,
    partTitleEs: 'Parte 9 — Explica por qué',
    partTitleHy: 'Մաս 9 — Բացատրի՛ր՝ ինչու',
    questionEs: '¿Por qué «frío» y «caliente» son antónimos?',
    questionHy: 'Ինչո՞ւ են «frío» և «caliente» բառերը հականիշներ։',
    answer: 'Porque expresan significados opuestos.',
    explanationEs: 'Representan los dos extremos contrarios de la escala térmica.',
    explanationHy: 'Որովհետև արտահայտում են հակառակ իմաստներ (ջերմային հակադրություն)։',
  },
  {
    id: 38,
    part: 9,
    partTitleEs: 'Parte 9 — Explica por qué',
    partTitleHy: 'Մաս 9 — Բացատրի՛ր՝ ինչու',
    questionEs: '¿Por qué «pan, panadero, panadería» forman una familia léxica?',
    questionHy: 'Ինչո՞ւ են «pan, panadero, panadería» բառերը կազմում բառակազմական ընտանիք։',
    answer: 'Porque comparten la misma raíz.',
    explanationEs: 'Todas derivan de la misma raíz o lexema «pan-».',
    explanationHy: 'Որովհետև ունեն նույն արմատը (pan-)։',
  },
  {
    id: 39,
    part: 9,
    partTitleEs: 'Parte 9 — Explica por qué',
    partTitleHy: 'Մաս 9 — Բացատրի՛ր՝ ինչու',
    questionEs: '¿Por qué «fútbol, tenis, baloncesto» forman un campo semántico?',
    questionHy: 'Ինչո՞ւ են «fútbol, tenis, baloncesto» բառերը կազմում իմաստային դաշտ։',
    answer: 'Porque todas son palabras relacionadas con los deportes.',
    explanationEs: 'Pertenecen al mismo ámbito temático deportivo, aunque no comparten la misma raíz.',
    explanationHy: 'Որովհետև բոլորն իմաստով կապված են սպորտի հետ (նույն թեման)։',
  },

  // Parte 10 — Mini examen rápido / Մաս 10 — Արագ քննություն
  {
    id: 40,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '40. feliz – contento → __________',
    questionHy: '40. feliz – contento → որոշի՛ր հարաբերությունը',
    answer: 'sinónimos',
    explanationEs: 'Tienen significado similar.',
    explanationHy: 'հոմանիշներ',
  },
  {
    id: 41,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '41. subir – bajar → __________',
    questionHy: '41. subir (բարձրանալ) – bajar (իջնել) → որոշի՛ր',
    answer: 'antónimos',
    explanationEs: 'Significados opuestos.',
    explanationHy: 'հականիշներ',
  },
  {
    id: 42,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '42. banco → asiento / entidad financiera → __________',
    questionHy: '42. banco → նստարան / բանկ → ինչպիսի՞ երևույթ է',
    answer: 'polisemia',
    explanationEs: 'Una sola palabra con múltiples sentidos.',
    explanationHy: 'բազմիմաստություն (polisemia)',
  },
  {
    id: 43,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '43. flor – florista – florero → __________',
    questionHy: '43. flor – florista – florero → ի՞նչ են կազմում',
    answer: 'familia léxica',
    explanationEs: 'Misma raíz léxica.',
    explanationHy: 'բառակազմական ընտանիք',
  },
  {
    id: 44,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '44. rojo – azul – verde → __________',
    questionHy: '44. rojo – azul – verde → ի՞նչ են կազմում',
    answer: 'campo semántico',
    explanationEs: 'Campo semántico de colores.',
    explanationHy: 'իմաստային դաշտ (գույներ)',
  },
  {
    id: 45,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '45. termómetro → normalmente un significado principal → __________',
    questionHy: '45. termómetro → ունի սովորաբար մեկ հիմնական իմաստ →',
    answer: 'monosémica',
    explanationEs: 'Palabra con un único significado.',
    explanationHy: 'մենիմաստ (monosémica)',
  },
  {
    id: 46,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '46. gato = animal / herramienta → __________',
    questionHy: '46. gato = կենդանի / մեքենայի գործիք →',
    answer: 'polisemia',
    explanationEs: 'Palabra polisémica con significados asociados.',
    explanationHy: 'բազմիմաստություն (polisemia)',
  },
  {
    id: 47,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '47. rápido – veloz → __________',
    questionHy: '47. rápido – veloz →',
    answer: 'sinonimia',
    explanationEs: 'Relación de sinonimia.',
    explanationHy: 'հոմանիշություն (sinonimia)',
  },
  {
    id: 48,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '48. abrir – cerrar → __________',
    questionHy: '48. abrir – cerrar →',
    answer: 'antonimia',
    explanationEs: 'Relación de antonimia.',
    explanationHy: 'հականիշություն (antonimia)',
  },
  {
    id: 49,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '49. pan – panadero → __________',
    questionHy: '49. pan – panadero →',
    answer: 'familia léxica',
    explanationEs: 'Misma raíz común pan-.',
    explanationHy: 'բառակազմական ընտանիք',
  },
  {
    id: 50,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen rápido',
    partTitleHy: 'Մաս 10 — Արագ քննություն',
    questionEs: '50. ¿Qué ayuda a elegir el significado correcto de una palabra polisémica?',
    questionHy: '50. Ի՞նչն է օգնում ընտրել բազմիմաստ բառի ճիշտ իմաստը։',
    answer: 'el contexto / համատեքստը',
    explanationEs: 'El contexto en la oración determina el significado pretendido.',
    explanationHy: 'համատեքստը (el contexto)։',
  },
];
