import { ExerciseItem } from './types.ts';

export const practice1Items: ExerciseItem[] = [
  // Parte 1 — Elige la respuesta correcta / Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը
  {
    id: 1,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    questionEs: '¿Qué son «feliz» y «contento»?',
    questionHy: 'Ի՞նչ են «feliz» և «contento» բառերը միմյանց նկատմամբ։',
    options: [
      { key: 'a', textEs: 'a) Antónimos', textHy: 'Հականիշներ' },
      { key: 'b', textEs: 'b) Sinónimos', textHy: 'Հոմանիշներ' },
      { key: 'c', textEs: 'c) Homónimos', textHy: 'Համանուններ' },
      { key: 'd', textEs: 'd) Polisémicos', textHy: 'Բազմիմաստներ' },
    ],
    answer: 'b) Sinónimos',
    explanationEs: 'Feliz y contento tienen significados semejantes, por lo tanto son sinónimos.',
    explanationHy: 'Feliz և contento ունեն մոտ իմաստ (ուրախ / գոհ), հետևաբար դրանք հոմանիշներ են։',
  },
  {
    id: 2,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    questionEs: '¿Qué son «alto» y «bajo»?',
    questionHy: 'Ի՞նչ են «alto» (բարձրահասակ) և «bajo» (ցածրահասակ) բառերը։',
    options: [
      { key: 'a', textEs: 'a) Sinónimos', textHy: 'Հոմանիշներ' },
      { key: 'b', textEs: 'b) Familia léxica', textHy: 'Բառակազմական ընտանիք' },
      { key: 'c', textEs: 'c) Antónimos', textHy: 'Հականիշներ' },
      { key: 'd', textEs: 'd) Polisémicos', textHy: 'Բազմիմաստներ' },
    ],
    answer: 'c) Antónimos',
    explanationEs: 'Alto y bajo expresan significados opuestos o contrarios.',
    explanationHy: 'Alto և bajo արտահայտում են հակառակ իմաստներ, ուստի հականիշներ են։',
  },
  {
    id: 3,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    questionEs: 'Una palabra que tiene varios significados relacionados es:',
    questionHy: 'Բառը, որն ունի մի քանի իրար հետ կապված իմաստներ, կոչվում է՝',
    options: [
      { key: 'a', textEs: 'a) monosémica', textHy: 'մենիմաստ' },
      { key: 'b', textEs: 'b) polisémica', textHy: 'բազմիմաստ' },
      { key: 'c', textEs: 'c) antónima', textHy: 'հականիշ' },
      { key: 'd', textEs: 'd) sinónima', textHy: 'հոմանիշ' },
    ],
    answer: 'b) polisémica',
    explanationEs: 'Poli- significa muchos: la polisemia implica varios significados.',
    explanationHy: '«Poli-» նշանակում է շատ. բազմիմաստ բառն ունի մի քանի կապակցված իմաստներ։',
  },
  {
    id: 4,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    questionEs: '¿Cuál puede ser una palabra polisémica?',
    questionHy: 'Ո՞ր բառը կարող է լինել բազմիմաստ։',
    options: [
      { key: 'a', textEs: 'a) banco', textHy: 'banco (նստարան / բանկ)' },
      { key: 'b', textEs: 'b) termómetro', textHy: 'termómetro (ջերմաչափ)' },
      { key: 'c', textEs: 'c) oxígeno', textHy: 'oxígeno (թթվածին)' },
      { key: 'd', textEs: 'd) triángulo', textHy: 'triángulo (եռանկյուն)' },
    ],
    answer: 'a) banco',
    explanationEs: 'Banco puede ser un asiento o una entidad bancaria/financiera.',
    explanationHy: 'Banco կարող է նշանակել ինչպես նստարան, այնպես էլ բանկ (դրամատուն)։',
  },
  {
    id: 5,
    part: 1,
    partTitleEs: 'Parte 1 — Elige la respuesta correcta',
    partTitleHy: 'Մաս 1 — Ընտրի՛ր ճիշտ պատասխանը',
    questionEs: '¿Qué relación hay entre «rojo, azul, verde y amarillo»?',
    questionHy: 'Ի՞նչ կապ կա «rojo, azul, verde և amarillo» բառերի միջև։',
    options: [
      { key: 'a', textEs: 'a) Familia léxica', textHy: 'Բառակազմական ընտանիք' },
      { key: 'b', textEs: 'b) Campo semántico', textHy: 'Իմաստային դաշտ' },
      { key: 'c', textEs: 'c) Antónimos', textHy: 'Հականիշներ' },
      { key: 'd', textEs: 'd) Homónimos', textHy: 'Համանուններ' },
    ],
    answer: 'b) Campo semántico',
    explanationEs: 'Comparten el campo semántico de los colores (no tienen la misma raíz).',
    explanationHy: 'Կազմում են գույների իմաստային դաշտը (նրանք չունեն նույն արմատը, բայց նույն թեմային են)։',
  },

  // Parte 2 — Sinónimo o antónimo / Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ
  {
    id: 6,
    part: 2,
    partTitleEs: 'Parte 2 — Sinónimo o antónimo',
    partTitleHy: 'Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ',
    questionEs: 'rápido – veloz → __________',
    questionHy: 'rápido (արագ) – veloz (սրընթաց) → Որոշի՛ր հարաբերությունը։',
    answer: 'Sinónimos / Հոմանիշներ',
    explanationEs: 'Ambas palabras expresan velocidad y rapidez.',
    explanationHy: 'Երկու բառերն էլ նշանակում են արագաշարժություն, հետևաբար հոմանիշներ են։',
  },
  {
    id: 7,
    part: 2,
    partTitleEs: 'Parte 2 — Sinónimo o antónimo',
    partTitleHy: 'Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ',
    questionEs: 'frío – caliente → __________',
    questionHy: 'frío (սառը) – caliente (տաք) → Որոշի՛ր հարաբերությունը։',
    answer: 'Antónimos / Հականիշներ',
    explanationEs: 'Son dos conceptos térmicos directamente opuestos.',
    explanationHy: 'Արտահայտում են ջերմաստիճանային հակառակ իմաստներ (հականիշներ)։',
  },
  {
    id: 8,
    part: 2,
    partTitleEs: 'Parte 2 — Sinónimo o antónimo',
    partTitleHy: 'Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ',
    questionEs: 'alegre – feliz → __________',
    questionHy: 'alegre (ուրախ) – feliz (երջանիկ/ուրախ) → Որոշի՛ր հարաբերությունը։',
    answer: 'Sinónimos / Հոմանիշներ',
    explanationEs: 'Indican un estado de ánimo positivo y alegre.',
    explanationHy: 'Արտահայտում են ուրախ տրամադրություն (հոմանիշներ)։',
  },
  {
    id: 9,
    part: 2,
    partTitleEs: 'Parte 2 — Sinónimo o antónimo',
    partTitleHy: 'Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ',
    questionEs: 'entrar – salir → __________',
    questionHy: 'entrar (մտնել) – salir (դուրս գալ) → Որոշի՛ր հարաբերությունը։',
    answer: 'Antónimos / Հականիշներ',
    explanationEs: 'Indican direcciones de movimiento opuestas.',
    explanationHy: 'Շարժման հակառակ ուղղություններ ցույց տվող բառեր (հականիշներ)։',
  },
  {
    id: 10,
    part: 2,
    partTitleEs: 'Parte 2 — Sinónimo o antónimo',
    partTitleHy: 'Մաս 2 — Հոմանի՞շ, թե՞ հականի՞շ',
    questionEs: 'comenzar – empezar → __________',
    questionHy: 'comenzar (սկսել) – empezar (սկսել) → Որոշի՛ր հարաբերությունը։',
    answer: 'Sinónimos / Հոմանիշներ',
    explanationEs: 'Ambos verbos significan dar inicio a una acción.',
    explanationHy: 'Երկու բայերն էլ նշանակում են որևէ գործողություն սկսել (հոմանիշներ)։',
  },

  // Parte 3 — Busca un sinónimo / Մաս 3 — Գտի՛ր հոմանիշ
  {
    id: 11,
    part: 3,
    partTitleEs: 'Parte 3 — Busca un sinónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հոմանիշ',
    questionEs: 'Sustituye la palabra destacada por un sinónimo: «El examen fue muy difícil.» → difícil → __________',
    questionHy: 'Փոխարինի՛ր առանձնացված բառը հոմանիշով․ «Քննությունը շատ դժվար էր»։ difícil → __________',
    answer: 'complicado',
    explanationEs: 'Respuesta posible: complicado (difícil = complicado).',
    explanationHy: 'դժվար (difícil) → բարդ (complicado)։',
  },
  {
    id: 12,
    part: 3,
    partTitleEs: 'Parte 3 — Busca un sinónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հոմանիշ',
    questionEs: '«Carlos está muy contento.» → contento → __________',
    questionHy: '«Կառլոսը շատ գոհ/ուրախ է»։ contento → __________',
    answer: 'feliz (o alegre)',
    explanationEs: 'contento es sinónimo de feliz o alegre.',
    explanationHy: 'contento (գոհ/ուրախ) բառի հոմանիշն է՝ feliz կամ alegre։',
  },
  {
    id: 13,
    part: 3,
    partTitleEs: 'Parte 3 — Busca un sinónimo',
    partTitleHy: 'Մաս 3 — Գտի՛ր հոմանիշ',
    questionEs: '«El coche es muy rápido.» → rápido → __________',
    questionHy: '«Ավտոմեքենան շատ արագ է»։ rápido → __________',
    answer: 'veloz',
    explanationEs: 'rápido es sinónimo de veloz.',
    explanationHy: 'rápido (արագ) բառի հոմանիշն է՝ veloz (սրընթաց)։',
  },

  // Parte 4 — Busca un antónimo / Մաս 4 — Գտի՛ր հականիշ
  {
    id: 14,
    part: 4,
    partTitleEs: 'Parte 4 — Busca un antónimo',
    partTitleHy: 'Մաս 4 — Գտի՛ր հականիշ',
    questionEs: 'grande → __________',
    questionHy: 'grande (մեծ) → գտի՛ր հականիշը',
    answer: 'pequeño',
    explanationEs: 'El antónimo de grande es pequeño.',
    explanationHy: 'մեծ (grande) → փոքր (pequeño)։',
  },
  {
    id: 15,
    part: 4,
    partTitleEs: 'Parte 4 — Busca un antónimo',
    partTitleHy: 'Մաս 4 — Գտի՛ր հականիշ',
    questionEs: 'cerca → __________',
    questionHy: 'cerca (մոտ) → գտի՛ր հականիշը',
    answer: 'lejos',
    explanationEs: 'El antónimo de cerca es lejos.',
    explanationHy: 'մոտ (cerca) → հեռու (lejos)։',
  },
  {
    id: 16,
    part: 4,
    partTitleEs: 'Parte 4 — Busca un antónimo',
    partTitleHy: 'Մաս 4 — Գտի՛ր հականիշ',
    questionEs: 'subir → __________',
    questionHy: 'subir (բարձրանալ) → գտի՛ր հականիշը',
    answer: 'bajar',
    explanationEs: 'El antónimo de subir es bajar.',
    explanationHy: 'բարձրանալ (subir) → իջնել (bajar)։',
  },
  {
    id: 17,
    part: 4,
    partTitleEs: 'Parte 4 — Busca un antónimo',
    partTitleHy: 'Մաս 4 — Գտի՛ր հականիշ',
    questionEs: 'fácil → __________',
    questionHy: 'fácil (հեշտ) → գտի՛ր հականիշը',
    answer: 'difícil',
    explanationEs: 'El antónimo de fácil es difícil.',
    explanationHy: 'հեշտ (fácil) → դժվար (difícil)։',
  },
  {
    id: 18,
    part: 4,
    partTitleEs: 'Parte 4 — Busca un antónimo',
    partTitleHy: 'Մաս 4 — Գտի՛ր հականիշ',
    questionEs: 'encender → __________',
    questionHy: 'encender (միացնել/վառել) → գտի՛ր հականիշը',
    answer: 'apagar',
    explanationEs: 'El antónimo de encender es apagar.',
    explanationHy: 'միացնել/վառել (encender) → անջատել/հանգցնել (apagar)։',
  },

  // Parte 5 — Polisemia: descubre el significado / Մաս 5 — Բազմիմաստություն
  {
    id: 19,
    part: 5,
    partTitleEs: 'Parte 5 — Polisemia: descubre el significado',
    partTitleHy: 'Մաս 5 — Բազմիմաստություն․ որոշի՛ր իմաստը',
    questionEs: '«Me duele la cabeza.» ¿Qué significa «cabeza»?',
    questionHy: '«Գլուխս ցավում է»։ Ի՞նչ է նշանակում «cabeza» այս նախադասությունում։',
    options: [
      { key: 'a', textEs: 'a) Parte del cuerpo', textHy: 'Մարմնի մաս (գլուխ)' },
      { key: 'b', textEs: 'b) Jefe de un grupo', textHy: 'Խմբի ղեկավար' },
      { key: 'c', textEs: 'c) Parte de una mesa', textHy: 'Սեղանի մաս' },
      { key: 'd', textEs: 'd) Dinero', textHy: 'Գումար' },
    ],
    answer: 'a) Parte del cuerpo',
    explanationEs: 'Aquí «cabeza» se refiere a la parte superior del cuerpo humano.',
    explanationHy: 'Այստեղ «cabeza» նշանակում է մարդու մարմնի վերին մասը (գլուխ)։',
  },
  {
    id: 20,
    part: 5,
    partTitleEs: 'Parte 5 — Polisemia: descubre el significado',
    partTitleHy: 'Մաս 5 — Բազմիմաստություն․ որոշի՛ր իմաստը',
    questionEs: '«Laura es la cabeza del equipo.» ¿Qué significa aquí «cabeza»?',
    questionHy: '«Լաուրան թիմի ղեկավարն է (գլուխն է)»։ Ի՞նչ է նշանակում այստեղ «cabeza»։',
    options: [
      { key: 'a', textEs: 'a) Parte del cuerpo', textHy: 'Մարմնի մաս' },
      { key: 'b', textEs: 'b) Persona que dirige', textHy: 'Ղեկավարող անձ / առաջնորդ' },
      { key: 'c', textEs: 'c) Sombrero', textHy: 'Գլխարկ' },
      { key: 'd', textEs: 'd) Lugar', textHy: 'Վայր' },
    ],
    answer: 'b) Persona que dirige',
    explanationEs: 'Cabeza se usa metafóricamente como líder o persona al mando.',
    explanationHy: 'Այստեղ cabeza նշանակում է ղեկավար կամ գլխավոր անձ։',
  },
  {
    id: 21,
    part: 5,
    partTitleEs: 'Parte 5 — Polisemia: descubre el significado',
    partTitleHy: 'Մաս 5 — Բազմիմաստություն․ որոշի՛ր իմաստը',
    questionEs: '«Nos sentamos en un banco del parque.» ¿Qué significa «banco»?',
    questionHy: '«Մենք նստեցինք այգու նստարանին»։ Ի՞նչ է նշանակում «banco»։',
    options: [
      { key: 'a', textEs: 'a) entidad financiera', textHy: 'ֆինանսական կազմակերպություն' },
      { key: 'b', textEs: 'b) asiento', textHy: 'նստարան' },
      { key: 'c', textEs: 'c) escuela', textHy: 'դպրոց' },
      { key: 'd', textEs: 'd) tienda', textHy: 'խանութ' },
    ],
    answer: 'b) asiento',
    explanationEs: 'Se refiere al mueble público diseñado para sentarse.',
    explanationHy: 'Նստարան՝ այգում նստելու համար նախատեսված կահույք։',
  },
  {
    id: 22,
    part: 5,
    partTitleEs: 'Parte 5 — Polisemia: descubre el significado',
    partTitleHy: 'Մաս 5 — Բազմիմաստություն․ որոշի՛ր իմաստը',
    questionEs: '«Mi padre trabaja en un banco.» «banco» significa: __________',
    questionHy: '«Հայրս աշխատում է բանկում»։ «banco» նշանակում է՝ __________',
    answer: 'entidad financiera',
    explanationEs: 'En este contexto laboral y económico, banco es una entidad financiera.',
    explanationHy: 'Այս համատեքստում banco նշանակում է դրամատուն, ֆինանսական հիմնարկ։',
  },

  // Parte 6 — Campo semántico / Մաս 6 — Իմաստային դաշտ
  {
    id: 23,
    part: 6,
    partTitleEs: 'Parte 6 — Campo semántico',
    partTitleHy: 'Մաս 6 — Իմաստային դաշտ',
    questionEs: '¿Qué palabra NO pertenece al mismo campo semántico? «fútbol – tenis – baloncesto – ventana»',
    questionHy: 'Ո՞ր բառը ՉԻ պատկանում նույն իմաստային դաշտին․ fútbol – tenis – baloncesto – ventana',
    answer: 'ventana',
    explanationEs: 'Ventana es una abertura en la pared. Los demás son deportes.',
    explanationHy: 'ventana (պատուհան). Մնացած բառերը սպորտաձևեր են։',
  },
  {
    id: 24,
    part: 6,
    partTitleEs: 'Parte 6 — Campo semántico',
    partTitleHy: 'Մաս 6 — Իմաստային դաշտ',
    questionEs: '¿A qué campo semántico pertenecen? «padre – madre – hermano – abuelo»',
    questionHy: 'Ո՞ր իմաստային դաշտին են պատկանում․ padre – madre – hermano – abuelo',
    answer: 'familia',
    explanationEs: 'Todas son palabras que designan parentescos familiares.',
    explanationHy: 'Ընտանիք (familia)՝ ընտանեկան ազգակցական կապեր։',
  },
  {
    id: 25,
    part: 6,
    partTitleEs: 'Parte 6 — Campo semántico',
    partTitleHy: 'Մաս 6 — Իմաստային դաշտ',
    questionEs: '¿A qué campo semántico pertenecen? «avión – tren – autobús – bicicleta»',
    questionHy: 'Ո՞ր իմաստային դաշտին են պատկանում․ avión – tren – autobús – bicicleta',
    answer: 'medios de transporte',
    explanationEs: 'Son todos vehículos para transportar personas o mercancías.',
    explanationHy: 'Տրանսպորտային միջոցներ (medios de transporte)։',
  },
  {
    id: 26,
    part: 6,
    partTitleEs: 'Parte 6 — Campo semántico',
    partTitleHy: 'Մաս 6 — Իմաստային դաշտ',
    questionEs: 'Busca el intruso: «mesa – silla – armario – naranja»',
    questionHy: 'Գտի՛ր ավելորդ բառը․ mesa – silla – armario – naranja',
    answer: 'naranja',
    explanationEs: 'Naranja es una fruta. Los demás son muebles.',
    explanationHy: 'naranja (նարինջ)՝ միրգ է, իսկ մնացածը կահույք (muebles) են։',
  },

  // Parte 7 — Familia léxica / Մաս 7 — Բառակազմական ընտանիք
  {
    id: 27,
    part: 7,
    partTitleEs: 'Parte 7 — Familia léxica',
    partTitleHy: 'Մաս 7 — Բառակազմական ընտանիք',
    questionEs: '¿Cuál pertenece a la familia léxica de «pan»?',
    questionHy: 'Ո՞ր բառն է պատկանում «pan» (հաց) բառի բառակազմական ընտանիքին։',
    options: [
      { key: 'a', textEs: 'a) comida', textHy: 'comida (ուտելիք)' },
      { key: 'b', textEs: 'b) panadería', textHy: 'panadería (հացի փուռ / խանութ)' },
      { key: 'c', textEs: 'c) leche', textHy: 'leche (կաթ)' },
      { key: 'd', textEs: 'd) plato', textHy: 'plato (ափսե)' },
    ],
    answer: 'b) panadería',
    explanationEs: 'Panadería comparte la misma raíz «pan-».',
    explanationHy: 'panadería ունի նույն «pan-» արմատը։',
  },
  {
    id: 28,
    part: 7,
    partTitleEs: 'Parte 7 — Familia léxica',
    partTitleHy: 'Մաս 7 — Բառակազմական ընտանիք',
    questionEs: '¿Qué palabras pertenecen a la misma familia?',
    questionHy: 'Ո՞ր շարքի բառերն են պատկանում նույն ընտանիքին։',
    options: [
      { key: 'a', textEs: 'a) flor – florero – florista', textHy: 'flor – florero – florista' },
      { key: 'b', textEs: 'b) casa – mesa – puerta', textHy: 'casa – mesa – puerta' },
      { key: 'c', textEs: 'c) correr – rápido – atleta', textHy: 'correr – rápido – atleta' },
      { key: 'd', textEs: 'd) mar – río – lago', textHy: 'mar – río – lago' },
    ],
    answer: 'a) flor – florero – florista',
    explanationEs: 'Comparten la raíz común «flor-».',
    explanationHy: 'Կիսում են ընդհանուր «flor-» արմատը։',
  },
  {
    id: 29,
    part: 7,
    partTitleEs: 'Parte 7 — Familia léxica',
    partTitleHy: 'Մաս 7 — Բառակազմական ընտանիք',
    questionEs: '«mar, marinero, marítimo» ¿Es campo semántico o familia léxica?',
    questionHy: '«mar, marinero, marítimo» → Իմաստայի՞ն դաշտ է, թե՞ բառակազմական ընտանիք։',
    answer: 'Familia léxica',
    explanationEs: 'Tienen la misma raíz «mar-», por eso es familia léxica.',
    explanationHy: 'Նույն արմատից կազմված բառեր են (mar-), հետևաբար բառակազմական ընտանիք է։',
  },
  {
    id: 30,
    part: 7,
    partTitleEs: 'Parte 7 — Familia léxica',
    partTitleHy: 'Մաս 7 — Բառակազմական ընտանիք',
    questionEs: '«avión, barco, tren, autobús» ¿Es campo semántico o familia léxica?',
    questionHy: '«avión, barco, tren, autobús» → Իմաստայի՞ն դաշտ է, թե՞ բառակազմական ընտանիք։',
    answer: 'Campo semántico',
    explanationEs: 'Tienen raíces diferentes pero el mismo concepto: medios de transporte.',
    explanationHy: 'Իմաստով կապված են (տրանսպորտ), բայց ունեն տարբեր արմատներ, ուստի իմաստային դաշտ է։',
  },

  // Parte 8 — Texto tipo examen / Մաս 8 — Տեքստ՝ քննության նման
  {
    id: 31,
    part: 8,
    partTitleEs: 'Parte 8 — Texto tipo examen',
    partTitleHy: 'Մաս 8 — Տեքստ՝ քննության նման',
    questionEs: 'En el texto de Pablo: Busca dos palabras de significado parecido.',
    questionHy: 'Պաբլոյի տեքստից․ Գտի՛ր մոտ իմաստ ունեցող երկու բառ։',
    answer: 'alegre – contentos',
    explanationEs: 'Ambas palabras expresan felicidad en el texto.',
    explanationHy: 'Երկու բառերն էլ տեքստում արտահայտում են ուրախ տրամադրություն։',
  },
  {
    id: 32,
    part: 8,
    partTitleEs: 'Parte 8 — Texto tipo examen',
    partTitleHy: 'Մաս 8 — Տեքստ՝ քննության նման',
    questionEs: '¿Qué relación tienen «alegre» y «contentos»?',
    questionHy: 'Ի՞նչ հարաբերություն ունեն «alegre» և «contentos» բառերը։',
    answer: 'Sinonimia / Հոմանիշություն',
    explanationEs: 'Son sinónimos ya que comparten un significado similar.',
    explanationHy: 'Հոմանիշներ են (Sinonimia)։',
  },
  {
    id: 33,
    part: 8,
    partTitleEs: 'Parte 8 — Texto tipo examen',
    partTitleHy: 'Մաս 8 — Տեքստ՝ քննության նման',
    questionEs: 'En el texto aparece dos veces «banco». ¿Tiene el mismo significado?',
    questionHy: 'Տեքստում երկու անգամ հանդիպում է «banco» բառը։ Արդյո՞ք այն ունի նույն իմաստը։',
    answer: 'No. Primero entidad financiera y después asiento.',
    explanationEs: 'Primero fueron a sacar dinero (banco financiero) y luego se sentaron (asiento del parque).',
    explanationHy: 'Ո՛չ։ Առաջին դեպքում նշանակում է բանկ (դրամական հիմնարկ), երկրորդում՝ նստարան։',
  },
  {
    id: 34,
    part: 8,
    partTitleEs: 'Parte 8 — Texto tipo examen',
    partTitleHy: 'Մաս 8 — Տեքստ՝ քննության նման',
    questionEs: '¿Qué fenómeno representa «banco»?',
    questionHy: 'Ի՞նչ լեզվական երևույթ է ներկայացնում «banco» բառը։',
    answer: 'Polisemia / Բազմիմաստություն',
    explanationEs: 'Es una palabra polisémica porque tiene varios significados.',
    explanationHy: 'Բազմիմաստություն (Polisemia), քանի որ ունի մեկից ավելի իմաստներ։',
  },
  {
    id: 35,
    part: 8,
    partTitleEs: 'Parte 8 — Texto tipo examen',
    partTitleHy: 'Մաս 8 — Տեքստ՝ քննության նման',
    questionEs: 'Busca una palabra relacionada con posición vertical en el texto.',
    questionHy: 'Տեքստում գտի՛ր ուղղահայաց դիրքի հետ կապված բառ։',
    answer: 'alto / arriba',
    explanationEs: 'En el texto aparecen «alto» y «arriba» referidos a la altura de la montaña.',
    explanationHy: 'alto (բարձր) / arriba (վերևում) բառերը կապված են ուղղահայաց բարձրության հետ։',
  },

  // Parte 9 — Preguntas con trampa / Մաս 9 — Խորամանկ հարցեր
  {
    id: 36,
    part: 9,
    partTitleEs: 'Parte 9 — Preguntas con trampa',
    partTitleHy: 'Մաս 9 — Խորամանկ հարցեր',
    questionEs: '¿Son «pan» y «panadero» sinónimos?',
    questionHy: 'Արդյո՞ք «pan» (հաց) և «panadero» (հացթուխ) բառերը հոմանիշներ են։',
    answer: '❌ No. Pertenecen a la misma familia léxica, pero significan cosas diferentes.',
    explanationEs: 'Tienen la misma raíz (pan-), pero pan es un alimento y panadero es la persona que lo elabora.',
    explanationHy: '❌ Ո՛չ։ Դրանք նույն բառակազմական ընտանիքից են, բայց հոմանիշ չեն (հացը մթերք է, հացթուխը՝ մարդ)։',
  },
  {
    id: 37,
    part: 9,
    partTitleEs: 'Parte 9 — Preguntas con trampa',
    partTitleHy: 'Մաս 9 — Խորամանկ հարցեր',
    questionEs: '¿Son «perro, gato, caballo» una familia léxica?',
    questionHy: 'Արդյո՞ք «perro, gato, caballo» բառերը կազմում են բառակազմական ընտանիք։',
    answer: '❌ No. Forman un campo semántico de animales.',
    explanationEs: 'Tienen raíces totalmente distintas; están relacionados solo por su significado (animales).',
    explanationHy: '❌ Ո՛չ։ Նրանք չունեն նույն արմատը։ Կազմում են կենդանիների իմաստային դաշտ (campo semántico)։',
  },
  {
    id: 38,
    part: 9,
    partTitleEs: 'Parte 9 — Preguntas con trampa',
    partTitleHy: 'Մաս 9 — Խորամանկ հարցեր',
    questionEs: '¿Dos palabras sinónimas tienen que significar exactamente lo mismo en todos los contextos?',
    questionHy: 'Արդյո՞ք երկու հոմանիշ բառեր պետք է բոլոր իրավիճակներում ճշգրիտ նույն բանը նշանակեն։',
    answer: 'No necesariamente.',
    explanationEs: 'Muchas veces hay matices de significado y depende del contexto para que encaje bien.',
    explanationHy: 'Պարտադիր չէ։ Հոմանիշները հաճախ մոտ իմաստ ունեն, բայց բոլոր իրավիճակներում լիովին փոխարինելի չեն։',
  },
  {
    id: 39,
    part: 9,
    partTitleEs: 'Parte 9 — Preguntas con trampa',
    partTitleHy: 'Մաս 9 — Խորամանկ հարցեր',
    questionEs: 'Una palabra polisémica tiene varios significados. ¿El contexto ayuda a saber cuál es?',
    questionHy: 'Բազմիմաստ բառն ունի մի քանի իմաստ։ Արդյո՞ք համատեքստն օգնում է պարզել դրանցից որն է։',
    answer: '✅ Sí.',
    explanationEs: 'El contexto es la clave fundamental para interpretar el sentido exacto de una palabra polisémica.',
    explanationHy: '✅ Այո։ Համատեքստն օգնում է հասկանալ, թե տվյալ պահին բառի որ իմաստն է օգտագործվում։',
  },

  // Parte 10 — Mini examen final / Մաս 10 — Փոքր վերջնական քննություն
  {
    id: 40,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '40. feliz – contento → __________',
    questionHy: '40. feliz – contento → լրացրո՛ւ հարաբերությունը',
    answer: 'sinónimos',
    explanationEs: 'Tienen significado similar.',
    explanationHy: 'հոմանիշներ (sinónimos)',
  },
  {
    id: 41,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '41. abrir – cerrar → __________',
    questionHy: '41. abrir (բացել) – cerrar (փակել) → լրացրո՛ւ',
    answer: 'antónimos',
    explanationEs: 'Tienen significados opuestos.',
    explanationHy: 'հականիշներ (antónimos)',
  },
  {
    id: 42,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '42. Una palabra con varios significados → __________',
    questionHy: '42. Մի քանի իմաստ ունեցող բառը կոչվում է՝ __________',
    answer: 'polisémica',
    explanationEs: 'Es la definición de polisemia.',
    explanationHy: 'բազմիմաստ (polisémica)',
  },
  {
    id: 43,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '43. Palabras con una raíz común → __________',
    questionHy: '43. Ընդհանուր արմատ ունեցող բառերը կազմում են՝ __________',
    answer: 'familia léxica',
    explanationEs: 'Comparten lexema o raíz.',
    explanationHy: 'բառակազմական ընտանիք (familia léxica)',
  },
  {
    id: 44,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '44. Palabras relacionadas por su significado → __________',
    questionHy: '44. Իմաստով իրար հետ կապված բառերը կազմում են՝ __________',
    answer: 'campo semántico',
    explanationEs: 'Pertenecen a una misma categoría semántica.',
    explanationHy: 'իմաստային դաշտ (campo semántico)',
  },
  {
    id: 45,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '45. rojo, amarillo, verde → __________',
    questionHy: '45. rojo, amarillo, verde → ի՞նչ են կազմում',
    answer: 'campo semántico de los colores',
    explanationEs: 'Es el campo semántico de los colores.',
    explanationHy: 'գույների իմաստային դաշտ',
  },
  {
    id: 46,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '46. flor, florista, florero → __________',
    questionHy: '46. flor, florista, florero → ի՞նչ են կազմում',
    answer: 'familia léxica',
    explanationEs: 'Comparten la raíz «flor-».',
    explanationHy: 'բառակազմական ընտանիք (արմատ՝ flor-)',
  },
  {
    id: 47,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '47. banco = asiento / entidad financiera → __________',
    questionHy: '47. banco = նստարան / բանկ → ի՞նչ երևույթ է',
    answer: 'polisemia',
    explanationEs: 'Es un ejemplo claro de polisemia.',
    explanationHy: 'բազմիմաստություն (polisemia)',
  },
  {
    id: 48,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '48. bonito – hermoso → __________',
    questionHy: '48. bonito (գեղեցիկ) – hermoso (հիասքանչ) → ի՞նչ հարաբերություն է',
    answer: 'sinonimia',
    explanationEs: 'Son sinónimos.',
    explanationHy: 'հոմանիշություն (sinonimia)',
  },
  {
    id: 49,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '49. día – noche → __________',
    questionHy: '49. día (ցերեկ/օր) – noche (գիշեր) → ի՞նչ հարաբերություն է',
    answer: 'antonimia',
    explanationEs: 'Son términos opuestos.',
    explanationHy: 'հականիշություն (antonimia)',
  },
  {
    id: 50,
    part: 10,
    partTitleEs: 'Parte 10 — Mini examen final',
    partTitleHy: 'Մաս 10 — Փոքր վերջնական քննություն',
    questionEs: '50. ¿Qué nos ayuda a elegir el significado correcto de una palabra polisémica?',
    questionHy: '50. Ի՞նչն է մեզ օգնում ընտրել բազմիմաստ բառի ճիշտ իմաստը։',
    answer: 'El contexto / Համատեքստը',
    explanationEs: 'El contexto en el que se utiliza la palabra determina cuál de sus significados es el adecuado.',
    explanationHy: 'Համատեքստը (El contexto)՝ շրջապատող բառերն ու իրադրությունը։',
  },
];
